hieigergipgeirgoeigpeigpeogioergieprogierpgoerigepriogerpogreigpoergiporegierpogerpgerpogerigpoerigp=5

print(hieigergipgeirgoeigpeigpeogioergieprogierpgoerigepriogerpogreigpoergiporegierpogerpgerpogerigpoerigp)